### ISSUE TITLE
Add awesome_bot to find broken links

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/how-to-contribute-to-open-source#35]
The [awesome_bot project](https://github.com/dkhamsing/awesome_bot) aims to automatically validate links so that in the case that in the future, one of the links dies or moves, we'll know about it automatically. 

I've set this up before using TravisCI and it works pretty well. Just a thought.

**Comment by shubheksha** [comment]
This is great, we should definitely hook this to the repo!

**Comment by erictleung** [comment]
@shubheksha awesome! :smile: 

If someone wants to take this up, just create a `.travis.yml` file in the root of this repository with

```yml
language: ruby
rvm: 2.2
before_script: gem install awesome_bot
script: awesome_bot --allow-redirect --allow-ssl README.md
notifications:
  email: false
```

Additionally, we'll want to sync this to FreeCodeCamp's TravisCI, maybe @QuincyLarson can weigh in on if he can set this up?
